// Package http implements the HTTP router, middleware stack, and uniform error handling for Halp.
//
// FROZEN AFTER WAVE 0:
// DO NOT EDIT THIS FILE. In accordance with docs/AGENT-WORKFLOW.md § 3 and Issue #7:
// Every Phase 1 route from docs/API.md is mounted here once and for all.
// Feature tracks implement their endpoints exclusively within their own http/<group>.go file
// (e.g. account.go, handles.go, ping.go, subscriptions.go, stream.go, settings.go, public.go)
// and never edit router.go again. This rule prevents merge conflicts across a dozen parallel tracks.
package http

import (
	"net/http"
	"time"

	"github.com/go-chi/chi/v5"
	"github.com/halpworld/halpcheers/server/internal/obs"
)

// RouterDeps provides all dependencies and group handlers mounted by the router.
type RouterDeps struct {
	Metrics       *obs.Metrics
	Accounts      *AccountsHandler
	Handles       *HandlesHandler
	Ping          *PingHandler
	Subscriptions *SubscriptionsHandler
	Stream        *StreamHandler
	Settings      *SettingsHandler
	Groups        *GroupsHandler
	Contacts      *ContactsHandler
	Public        *PublicHandler
	MaxBodyBytes  int64
	ReqTimeout    time.Duration
}

// NewRouter constructs and configures the complete Chi router mounting all Phase 1 routes.
func NewRouter(deps RouterDeps) *chi.Mux {
	r := chi.NewRouter()

	// 1. Recovery
	r.Use(RecoveryMiddleware)

	// 2. Access Log (obs)
	r.Use(obs.AccessLogMiddleware(nil))

	// 3. Request Size Limit (default 64 KiB)
	maxBytes := deps.MaxBodyBytes
	if maxBytes <= 0 {
		maxBytes = 64 * 1024
	}
	r.Use(RequestSizeLimitMiddleware(maxBytes))

	// 4. Timeout
	timeout := deps.ReqTimeout
	if timeout <= 0 {
		timeout = 10 * time.Second
	}
	r.Use(TimeoutMiddleware(timeout))

	// 5. Bearer Auth Parse
	r.Use(BearerAuthParseMiddleware)

	// 6. PoW Header Parse
	r.Use(PoWHeaderParseMiddleware)

	// Operational / Health Endpoints
	r.Get("/healthz", func(w http.ResponseWriter, r *http.Request) {
		w.WriteHeader(http.StatusOK)
		_, _ = w.Write([]byte("ok\n"))
	})
	r.Get("/readyz", func(w http.ResponseWriter, r *http.Request) {
		w.WriteHeader(http.StatusOK)
		_, _ = w.Write([]byte("ready\n"))
	})
	if deps.Metrics != nil {
		r.Handle("/metrics", deps.Metrics.Handler())
	}

	// Default handlers if not supplied
	accountsH := deps.Accounts
	if accountsH == nil {
		accountsH = NewAccountsHandler()
	}
	handlesH := deps.Handles
	if handlesH == nil {
		handlesH = NewHandlesHandler()
	}
	pingH := deps.Ping
	if pingH == nil {
		pingH = NewPingHandler()
	}
	subsH := deps.Subscriptions
	if subsH == nil {
		subsH = NewSubscriptionsHandler()
	}
	streamH := deps.Stream
	if streamH == nil {
		streamH = NewStreamHandler()
	}
	settingsH := deps.Settings
	if settingsH == nil {
		settingsH = NewSettingsHandler()
	}
	groupsH := deps.Groups
	if groupsH == nil {
		groupsH = NewGroupsHandler()
	}
	contactsH := deps.Contacts
	if contactsH == nil {
		contactsH = NewContactsHandler()
	}
	publicH := deps.Public
	if publicH == nil {
		publicH = NewPublicHandler()
	}

	// -------------------------------------------------------------------------
	// Accounts routes (docs/API.md § Account)
	// -------------------------------------------------------------------------
	r.Post("/v1/accounts", accountsH.CreateAccount)
	r.Post("/v1/session", accountsH.CreateSession)
	r.Delete("/v1/session", accountsH.DeleteSession)
	r.Get("/v1/account", accountsH.GetAccount)
	r.Get("/v1/account/export", accountsH.ExportAccount)
	r.Delete("/v1/account", accountsH.DeleteAccount)

	// -------------------------------------------------------------------------
	// Handles & Aliases routes (docs/API.md § Handles and alias)
	// -------------------------------------------------------------------------
	r.Get("/v1/handles", handlesH.ListHandles)
	r.Post("/v1/handles", handlesH.CreateHandle)
	r.Patch("/v1/handles/{handle}", handlesH.UpdateHandle)
	r.Delete("/v1/handles/{handle}", handlesH.DeleteHandle)
	r.Put("/v1/alias", handlesH.SetAlias)
	r.Delete("/v1/alias", handlesH.DeleteAlias)

	// -------------------------------------------------------------------------
	// Sending route (docs/API.md § Sending)
	// -------------------------------------------------------------------------
	r.Post("/v1/ping/{target}", pingH.SendPing)

	// -------------------------------------------------------------------------
	// Receiving & Subscriptions routes (docs/API.md § Receiving)
	// -------------------------------------------------------------------------
	r.Post("/v1/subscriptions", subsH.CreateSubscription)
	r.Delete("/v1/subscriptions/{id}", subsH.DeleteSubscription)
	r.Get("/v1/stream", streamH.Stream)
	r.Get("/v1/pending", streamH.Pending)
	r.Get("/v1/settings", settingsH.GetSettings)
	r.Put("/v1/settings", settingsH.UpdateSettings)
	r.Post("/v1/handles/{handle}/report-abuse", settingsH.ReportAbuse)

	// -------------------------------------------------------------------------
	// Groups routes - Phase 2 (docs/API.md § Groups)
	// -------------------------------------------------------------------------
	r.Post("/v1/groups", groupsH.CreateGroup)
	r.Get("/v1/groups", groupsH.ListGroups)
	r.Get("/v1/groups/{id}/members", groupsH.ListMembers)
	r.Post("/v1/groups/join", groupsH.JoinGroup)
	r.Delete("/v1/groups/{id}/membership", groupsH.LeaveGroup)
	r.Delete("/v1/groups/{id}/members/{member}", groupsH.RemoveMember)
	r.Post("/v1/groups/{id}/invite", groupsH.RotateInvite)
	r.Patch("/v1/groups/{id}", groupsH.UpdateGroup)
	r.Delete("/v1/groups/{id}", groupsH.DeleteGroup)

	// -------------------------------------------------------------------------
	// Contacts routes - Phase 2 (docs/API.md § Contacts)
	// -------------------------------------------------------------------------
	r.Get("/v1/contacts", contactsH.GetContacts)
	r.Put("/v1/contacts", contactsH.UpdateContacts)
	r.Delete("/v1/contacts", contactsH.DeleteContacts)

	// -------------------------------------------------------------------------
	// Public routes (docs/API.md § Public)
	// -------------------------------------------------------------------------
	r.Get("/h/{handle}", publicH.HandleLanding)
	r.Get("/@{alias}", publicH.AliasLanding)
	r.Get("/badge/{handle}.svg", publicH.BadgeSVG)
	r.Get("/overlay/{token}", publicH.Overlay)

	return r
}
